spring:
  main.banner-mode: off
  datasource:
    url: jdbc:mysql://$HOST_BD/learningdb1?serverTimezone=UTC&user=$USER_BD&password=$PASSWORD_BD
    tomcat.connection-properties: useUnicode=true;characterEncoding=utf-8;
  sql.init.mode: always

  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    defer-datasource-initialization: true
    show-sql: true
  servlet: 
    multipart.max-file-size: 10MB
    multipart.max-request-size: 10MB

server:
  port: 8004
  error.include-message: always
