spring:
  main.banner-mode: off
  datasource:
    url: jdbc:mysql://b8xwx9ok737a.us-east-3.psdb.cloud/learningdb1?serverTimezone=UTC&user=jnf0eq5gna15&password=pscale_pw_XtkUW3unXvznQYnTCZLLGpohVRPsnxEILumdjb_DmrE
    tomcat.connection-properties: useUnicode=true;characterEncoding=utf-8;
  sql.init.mode: always

  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    defer-datasource-initialization: true
    show-sql: true
  servlet: 
    multipart.max-file-size: 10MB
    multipart.max-request-size: 10MB

server:
  port: 8004
  error.include-message: always

# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.datasource.url=jdbc:mysql://b8xwx9ok737a.us-east-3.psdb.cloud/learningdb1
# spring.datasource.username=nliwf2whs41c
# spring.datasource.password=pscale_pw_lnGq88ajeT9PiZU91tNRXYRRH2GMDo0uCz4JvyE9rn4
# spring.jpa.hibernate.ddl-auto=create-only
# spring.datasource.data=classpath:data.sql

# spring.datasource.url=jdbc:mysql://b8xwx9ok737a.us-east-3.psdb.cloud/learningdb1?serverTimezone=UTC
# spring.datasource.username=nliwf2whs41c
# spring.datasource.password=pscale_pw_lnGq88ajeT9PiZU91tNRXYRRH2GMDo0uCz4JvyE9rn4
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.jpa.database-platform=org.hibernate.dialect.MySQL57InnoDBDialect
# spring.jpa.hibernate.ddl-auto=create
# logging.level.org.hibernate.SQL=debug
# spring.servlet.multipart.max-file-size=10MB
# spring.servlet.multipart.max-request-size=10MB
# spring.datasource.tomcat.connection-properties=useUnicode=true;characterEncoding=utf-8;
# # server.port=8004
